---

- hosts: raspberrypi
  remote_user: pi
  tasks:
   - name: Install tools
     package:
       name: "{{ item }}"
       state: present
     with_items:
       - git
       - tmux
       - ansible
       - vim
       - mtr
       - nmap
       - tree
       - python3
       - python3-pip
       - silversearcher-ag
       - npm
       - owncloud-client-cmd
       - zsh
       - fonts-powerline
       - buku
     become: yes

   - name: Install Git tools
     pip:
       name: thefuck
       executable: pip3
     with_items:
       - thefuck
       - ddgr
     become: yes

#   - name: Install Tmuxinator
#     gem:
#       name: tmuxinator
#       state: present
#     become: yes

   - name: Install npm tools
     npm:
       name: tldr
       global: yes
     become: yes

   - name: create dotfile directory
     file:
       path: /home/pi/dotfiles
       owner: pi
       group: pi

   - name: Configure tmux configuration
     file:
       path: /home/pi/dotfiles/tmux.conf
       owner: pi
       group: pi

   - name: Set vim config
     file:
       path: /home/pi/dotfiles/vim.rc
       owner: pi
       group: pi

   - name: download tmux theme pack
     git:
       repo: 'https://github.com/jimeh/tmux-themepack.git'
       dest: /home/pi/git/tmux-themepack

   - name: Download oh-my-zsh
     git:
       repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
       dest: /home/pi/git/oh-my-zsh

   - name: Setting up oh-my-zsh Symmlink
     file:
       src: '/home/pi/git/oh-my-zsh'
       dest: /home/pi/.oh-my-zsh
       state: link

   - name: Download Powerlevel9k
     git:
       repo: 'https://github.com/bhilburn/powerlevel9k.git'
       dest: /home/pi/.oh-my-zsh/custom/themes/powerlevel9k

   - name: Download Powerlevel10k
     git:
       repo: 'https://github.com/romkatv/powerlevel10k.git'
       dest: /home/pi/.oh-my-zsh/custom/themes/powerlevel10k

   - name: Download fzf
     git:
       repo: 'https://github.com/junegunn/fzf.git'
       dest: /home/pi/git/fzf
     register: fzf_download

   - debug:
       msg: Install fzf finder with "~/.fzf/install"
     when: fzf_download.changed

   - name: Install Vundle
     git:
       repo: 'https://github.com/VundleVim/Vundle.vim.git'
       dest: /home/pi/.vim/bundle/Vundle.vim

   - name: Set link for Dotfiles
     file:
       src: '/home/pi/dotfiles/{{ item.src }}'
       dest: '{{ item.dest }}'
       state: link
     with_items:
       - { src: 'tmux.conf', dest: '/home/pi/.tmux.conf' }
       - { src: 'vim.rc', dest: '/home/pi/.vimrc' }
       - { src: 'zsh.rc', dest: 'home/pi/.zshrc'}

   - name: Creation of own bin files
     file:
       path: /home/pi/bin
       owner: pi
       group: pi
       state: directory

   - name: Installation cht.sh
     get_url:
       url: https://cht.sh/:cht.sh
       dest: /home/pi/bin/cht.sh
       mode: 0700

   - name: Download of Pet (Snippit manager)
     get_url:
       url: https://github.com/knqyf263/pet/releases/download/v0.3.0/pet_0.3.0_linux_amd64.deb
       dest: /tmp/pet_0.3.0_linux_amd64.deb

   - name: Install Pet
     command: dpkg -i /tmp/pet_0.3.0_linux_amd64.deb
